<a href="https://colab.research.google.com/github/Bigmee/Data-analysis-python-/blob/main/numpy%20library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 2**7
print(x)

128


In [7]:
import sys
import numpy
import numpy as np


In [8]:

np.array([1,2,3,4,5,6,7,7])


array([1, 2, 3, 4, 5, 6, 7, 7])

In [9]:
a = np.array([0,23,4,5,6,7])
a[0],a[3]

(0, 5)

In [10]:

a[[0, 1, 3, -1]]

array([ 0, 23,  5,  7])

In [11]:
a.dtype

dtype('int64')

In [13]:
np.array([0,3, 5,], dtype = float)

array([0., 3., 5.])

Multidimensional array


In [22]:
b = np.array([[1,3,4,4,4],
             [5,6,7,6,6]])


In [23]:
b.shape

(2, 5)

In [24]:
b.size

10

3 dimentional array

In [25]:
c =np.array([[
    [1,2,3,4],
    [1,2,4,5]
],
   [
       [3,4,5,6],
    [7,8,8,8]
       
   ]      
         
         
         ])

In [26]:
c.size

16

In [27]:
c.shape

(2, 2, 4)

In [30]:
c[1][0]

array([3, 4, 5, 6])

In [31]:
b[0:-1]

array([[1, 3, 4, 4, 4]])

In [32]:
a[:1]

array([0])

In [33]:
b[:2]

array([[1, 3, 4, 4, 4],
       [5, 6, 7, 6, 6]])

In [34]:
c[:2]

array([[[1, 2, 3, 4],
        [1, 2, 4, 5]],

       [[3, 4, 5, 6],
        [7, 8, 8, 8]]])

In [36]:
c[:, :1]

array([[[1, 2, 3, 4]],

       [[3, 4, 5, 6]]])

In [41]:
c[:0, :0]

array([], shape=(0, 0, 4), dtype=int64)

In [42]:
c[0][0]

array([1, 2, 3, 4])

In [43]:
c[0:0]

array([], shape=(0, 2, 4), dtype=int64)

In [45]:
c[0][0][0]

1

In [46]:
c[0] = 99

In [47]:
c[0]

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [50]:
c.sum()

841

In [51]:
c.mean()

52.5625

In [52]:
c.std()

46.45558194393866

In [55]:
c.sum(axis=0)


array([[102, 103, 104, 105],
       [106, 107, 107, 107]])

In [56]:
c.std(axis=1)

array([[0. , 0. , 0. , 0. ],
       [2. , 2. , 1.5, 1. ]])

In [63]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Broadcasting and Vectorising Operations 

In [73]:
x = np.arange(7)

In [74]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [77]:
x+100

array([100, 101, 102, 103, 104, 105, 106])

In [78]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [79]:
l = [1, 2, 3, 4]

In [81]:
[i * 10 for i in x]

[0, 10, 20, 30, 40, 50, 60]

Boolean


In [83]:
w = np.arange(4)


In [84]:
w

array([0, 1, 2, 3])

In [86]:
w[[True, False, False, True]]

array([0, 3])